### PR TITLE
add allcombinations

### PR DESCRIPTION
**Pull request by bkamins**
add `allcombinations` function. see https://github.com/JuliaData/DataFrames.jl/pull/3031 for an example implementation.

### CODE REVIEW

**Comment by bkamins** [comment]
@nalimilan - now I realized that the approach proposed here (and discussed on slack) cannot be used.
The reason is that we cannot dispatch on `DataFrame` since its type is `DataType` (it is not a function).

Maybe we should leave https://github.com/JuliaData/DataFrames.jl/pull/3031 as it is then? Or do you see any other solution? The only I can see is that `allcombinations` would define a table-like type that then would be passed to `DataFrame` constructor. But then we would need to provide implementation of the logic of the function in DataAPI.jl, which I think we should not do.

**Comment by nalimilan** [comment]
Can't we just define methods like `allcombinations(::Type{DataFrame}, ...)`?

**Comment by bkamins** [comment]
Ah - right. We can 😄. In this case can you please review this PR?

**Review by nalimilan — APPROVED** [review]

**Comment by nalimilan** [comment]
@quinnj We could mention in the docstring that TableOperations owns `allcombinations(NamedTuple, ...)` and implement a method there.

**Comment by bkamins** [comment]
@quinnj - could you have a look at this PR before I merge it and make a release (and finish https://github.com/JuliaData/DataFrames.jl/pull/3031 a follow-up PR in DataFrames.jl)? Thank you!

**Review by quinnj — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
